export const routes = {
    NAVIGATION_HOME_SCREEN_PATH: "NAVIGATION_HOME_SCREEN_PATH",
    NAVIGATION_SETTINGS_SCREEN_PATH: "NAVIGATION_SETTINGS_SCREEN_PATH",
    NAVIGATION_TAB_NAVIGATION_PATH: "NAVIGATION_TAB_NAVIGATION_PATH",
    NAVIGATION_WELCOME_SCREEN_PATH: "NAVIGATION_WELCOME_SCREEN_PATH",
    //Authme
    NAVIGATION_AUTHME_SCREEN_PATH: "NAVIGATION_AUTHME_SCREEN_PATH",
    NAVIGATION_AUTHME_LOGIN_SCREEN_PATH: "NAVIGATION_AUTHME_LOGIN_SCREEN_PATH",
}